In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
import altair as alt
from altair import datum

In [2]:
papers = pd.read_csv('../data/papers_to_study_expanded.csv')
set(papers.journal)

{'Communication Theory',
 'Communication, Culture and Critique',
 'Human Communication Research',
 'Journal of Communication',
 'Journal of Computer-Mediated Communication'}

In [3]:
# joc
joc = papers[papers.journal == 'Journal of Communication'].sort_values(by="year", ascending= True)
joc.head(1)

,journal,year,category,type,cross_country,cross_type,cross_gender,cross_race,num_race,num_country,...,cross_gender_race_and_country,numberOfAuthors,first_author_gender,first_author_race,first_author_country,first_author_afftype,with_us_authors,cross_race_details,cross_gender_details,gscholar_citation
2625,Journal of Communication,1951,Articles,R,False,True,False,False,1,1,...,False,2.0,M,White,US,Education,True,White only,M only,0.0

In [4]:
# ccc
ccc = papers[papers.journal == 'Communication, Culture and Critique'].sort_values(by="year", ascending= True)
ccc.head(1)

,journal,year,category,type,cross_country,cross_type,cross_gender,cross_race,num_race,num_country,...,cross_gender_race_and_country,numberOfAuthors,first_author_gender,first_author_race,first_author_country,first_author_afftype,with_us_authors,cross_race_details,cross_gender_details,gscholar_citation
5711,"Communication, Culture and Critique",2008,Original Articles,R,False,False,False,False,1,1,...,False,1.0,M,White,US,Education,True,White only,M only,52.0

In [5]:
ccc.shape

(459, 23)

In [6]:
hcr = papers[papers.journal == 'Human Communication Research'].sort_values(by="year", ascending= True)
hcr.head(1)

,journal,year,category,type,cross_country,cross_type,cross_gender,cross_race,num_race,num_country,...,cross_gender_race_and_country,numberOfAuthors,first_author_gender,first_author_race,first_author_country,first_author_afftype,with_us_authors,cross_race_details,cross_gender_details,gscholar_citation
3778,Human Communication Research,1974,Articles,R,False,False,False,False,1,1,...,False,1.0,M,White,US,Education,True,White only,M only,8.0

In [7]:
jcmc = papers[papers.journal == 'Journal of Computer-Mediated Communication'].sort_values(by="year", ascending= True)
jcmc.head(1)

,journal,year,category,type,cross_country,cross_type,cross_gender,cross_race,num_race,num_country,...,cross_gender_race_and_country,numberOfAuthors,first_author_gender,first_author_race,first_author_country,first_author_afftype,with_us_authors,cross_race_details,cross_gender_details,gscholar_citation
5252,Journal of Computer-Mediated Communication,1995,Original Article,R,False,False,False,False,1,1,...,False,1.0,M,White,US,Education,True,White only,M only,20.0

In [8]:
ct = papers[papers.journal == 'Communication Theory'].sort_values(by="year", ascending= True)
ct.head(1)

,journal,year,category,type,cross_country,cross_type,cross_gender,cross_race,num_race,num_country,...,cross_gender_race_and_country,numberOfAuthors,first_author_gender,first_author_race,first_author_country,first_author_afftype,with_us_authors,cross_race_details,cross_gender_details,gscholar_citation
4407,Communication Theory,1991,Comparative Theory,R,False,False,False,False,1,1,...,False,1.0,F,White,US,Education,True,White only,F only,101.0