## AIM

With this notebook, I aim to 
 - Find authors without full name
 - find authors with first names being initials
 
### Note

On 2022-12-09, I found that this is incorrect. I should use `pd.concat([one_df, two_df])` rather than `isin(to_remove_dois)`.

In [1]:
import pandas as pd
from collections import Counter
import numpy as np

In [2]:
# df1 = pd.read_csv('../data/processed/author_with_pred.csv')
# df1[(df1.firstName.isnull()) | (df1.lastName.isnull())].doi

In [3]:
df = pd.read_csv('../data/processed/authors_to_study.csv')

In [4]:
df[(df.firstName.isnull()) | (df.lastName.isnull())]

,authorID,doi,url,year,title,journal,numberOfAuthors,authorPosition,authorFullName,firstName,...,white,raceHighest,raceSecondHighest,raceDiff,affProcessed,affiliation.2,ROR_AFFNAME,matchMethod,ROR_ID,type
3612,10.1111/j.1460-2466.1980.tb02015.x+2.0,10.1111/j.1460-2466.1980.tb02015.x,https://academic.oup.com/joc/article/30/4/50/4...,1980,Programming for Development in Indonesia,Journal of Communication,2.0,2.0,Alfian,NaN,...,0.220853,0.684015,0.220853,0.463161,national institute of economic and social rese...,2 National Institute of Economic and Social Re...,National Institute of Economic and Social Rese...,Exact,https://ror.org/048m81442,R

There is only one person whose name is not complete.

In [5]:
df = df[(df.firstName.notnull()) & (df.lastName.notnull())]

In [6]:
df['firstNameLength'] = df.apply(lambda row: len(row.firstName), axis = 1)

In [7]:
two_df = df[(df.firstName.str.contains('.', regex = False)) & (df.firstNameLength == 2)]
two_df.sample(3)

,authorID,doi,url,year,title,journal,numberOfAuthors,authorPosition,authorFullName,firstName,...,raceHighest,raceSecondHighest,raceDiff,affProcessed,affiliation.2,ROR_AFFNAME,matchMethod,ROR_ID,type,firstNameLength
3409,10.1111/j.1460-2466.1982.tb02515.x+1.0,10.1111/j.1460-2466.1982.tb02515.x,https://academic.oup.com/joc/article/32/4/22/4...,1982,Glued to the Box?: Patterns of TV Repeat-Viewing,Journal of Communication,3.0,1.0,T. P. Barwise,T.,...,0.895544,0.060819,0.834725,t p barwise is senior research officer at the ...,1 T. P. Barwise is Senior Research Officer at ...,London Business School,Exact,https://ror.org/001c2sn75,R,2
6522,10.1111/j.1468-2958.1996.tb00376.x+1.0,10.1111/j.1468-2958.1996.tb00376.x,https://academic.oup.com/hcr/article/22/4/482/...,1996,Psychological Processes Underlying Cultivation...,Human Communication Research,1.0,1.0,L. J. Shrum,L.,...,0.889826,0.060513,0.829313,l j shrum is an assistant professor in the dep...,"1 L. J. Shrum (Ph.D., University of Illinois a...",University of Business in Wrocław,API_QUERY,https://ror.org/04qxzae03,R,2
3776,10.1111/j.1460-2466.1979.tb01710.x+3.0,10.1111/j.1460-2466.1979.tb01710.x,https://academic.oup.com/joc/article/29/3/42/4...,1979,"Atrocity Tales, the Unification Church, and th...",Journal of Communication,3.0,3.0,J. C. Ventimiglia,J.,...,0.953322,0.026924,0.926398,assistant professor all in the department of s...,"1 Assistant Professor, all in the Department o...",The University of Texas at Arlington,Exact,https://ror.org/019kgqr73,R,2

In [8]:
two_df_doi = two_df.doi.tolist()

In [9]:
one_df_doi = df[df.firstNameLength == 1].doi.tolist()

In [11]:
## THIS IS WRONG!
to_remove_dois = list(set(two_df_doi + one_df_doi))
len(to_remove_dois)

70